name = "redl1zar-personal-links"
main = "worker/index.ts"
compatibility_date = "2026-09-12"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[kv_namespaces]]
binding = "SPOTIFY_KV"
id = "601e12ada8104731b002d35a5180f695"
