name = "redl1zar-links"
main = "worker/index.ts"
compatibility_date = "2026-09-12"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
PUBLIC_APP_ORIGIN = "https://xn--d1ax3b.fun"

[[routes]]
pattern = "api.xn--d1ax3b.fun"
custom_domain = true

[[kv_namespaces]]
binding = "SPOTIFY_KV"
id = "601e12ada8104731b002d35a5180f695"
